// front-end-angular-bank/src/app/components/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import {GenericsService} from '../../services/generics.service';
import {data} from '../../../data/dataAccount';


@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {

  public dataAccount: any;
  // public profile = useSelector((state) => state.user.profile);
  // public error = useSelector((state) => state.user.error);

  constructor(
    private genericsService: GenericsService
  ) { }

  ngOnInit(): void {
    // this.genericsService.getResource('/user/profile').then((response) => {
    //   console.log(response);
    // });
    this.dataAccount = data;
    console.log(this.dataAccount);
  }

}

<app-header></app-header>
<main class="main bg-dark">
  <div class="header">
    <h1>Welcome back<br />Tony Jarvis!</h1>
    <button class="edit-button">Edit Name</button>
  </div>
  <h2 class="sr-only">Accounts</h2>
  <ng-container>
    <section class="account" *ngFor="let item of dataAccount">
      <div class="account-content-wrapper">
        <h3 class="account-title">{{item.title}} &nbsp;&nbsp; ({{item.accountNumber}})</h3>
        <p class="account-amount">{{item.accountPrice}}</p>
        <p class="account-amount-description">{{item.subTitle}}</p>
      </div>
      <div class="account-content-wrapper cta">
        <button class="transaction-button">View transactions</button>
      </div>
    </section>
  </ng-container>
</main>
<app-footer></app-footer>

// front-end-bank/src/components/UserComponent/UserComponent.jsx
import React from "react";

export default function UserComponent() {
    return(
        <main className="main bg-dark">
            <div className="header">
                <h1>Welcome back<br/>Tony Jarvis!</h1>
                <button className="edit-button">Edit Name</button>
            </div>
            <h2 className="sr-only">Accounts</h2>
            <section className="account">
                <div className="account-content-wrapper">
                    <h3 className="account-title">Argent Bank Checking (x8349)</h3>
                    <p className="account-amount">$2,082.79</p>
                    <p className="account-amount-description">Available Balance</p>
                </div>
                <div className="account-content-wrapper cta">
                    <button className="transaction-button">View transactions</button>
                </div>
            </section>
            <section className="account">
                <div className="account-content-wrapper">
                    <h3 className="account-title">Argent Bank Savings (x6712)</h3>
                    <p className="account-amount">$10,928.42</p>
                    <p className="account-amount-description">Available Balance</p>
                </div>
                <div className="account-content-wrapper cta">
                    <button className="transaction-button">View transactions</button>
                </div>
            </section>
            <section className="account">
                <div className="account-content-wrapper">
                    <h3 className="account-title">Argent Bank Credit Card (x8349)</h3>
                    <p className="account-amount">$184.30</p>
                    <p className="account-amount-description">Current Balance</p>
                </div>
                <div className="account-content-wrapper cta">
                    <button className="transaction-button">View transactions</button>
                </div>
            </section>
        </main>
    )
}
