// front-end-angular-bank/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import {Router} from '@angular/router';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  public home = false;
  public url = '';
  constructor(
    private router: Router
  ) { }

  ngOnInit(): void {
    this.home = true;
    this.url = this.router.url;
    console.log(this.url);
  }

}

<app-header [home]="home"></app-header>
<main>
  <div class="hero">
    <section class="hero-content">
      <h2 class="sr-only">Promoted Content</h2>
      <p class="subtitle">No fees.</p>
      <p class="subtitle">No minimum deposit.</p>
      <p class="subtitle">High interest rates.</p>
      <p class="text">Open a savings account with Argent Bank today!</p>
    </section>
  </div>
  <section class="features">
    <h2 class="sr-only">Features</h2>
    <div class="feature-item">
      <img src="../../../assets/img/icon-chat.png" alt="Chat Icon" class="feature-icon" />
      <h3 class="feature-item-title">You are our #1 priority</h3>
      <p>
        Need to talk to a representative? You can get in touch through our
        24/7 chat or through a phone call in less than 5 minutes.
      </p>
    </div>
    <div class="feature-item">
      <img
        src="../../../assets/img/icon-money.png"
        alt="Chat Icon"
        class="feature-icon"
      />
      <h3 class="feature-item-title">More savings means higher rates</h3>
      <p>
        The more you save with us, the higher your interest rate will be!
      </p>
    </div>
    <div class="feature-item">
      <img
        src="../../../assets/img/icon-security.png"
        alt="Chat Icon"
        class="feature-icon"
      />
      <h3 class="feature-item-title">Security you can trust</h3>
      <p>
        We use top of the line encryption to make sure your data and money
        is always safe.
      </p>
    </div>
  </section>
</main>
<app-footer></app-footer>

// front-end-bank/src/components/HomeComponent/HomeComponent.jsx
export default function HomeComponent() {
    return(
        <main>
            <div className="hero">
                <section className="hero-content">
                    <h2 className="sr-only">Promoted Content</h2>
                    <p className="subtitle">No fees.</p>
                    <p className="subtitle">No minimum deposit.</p>
                    <p className="subtitle">High interest rates.</p>
                    <p className="text">Open a savings account with Argent Bank today!</p>
                </section>
            </div>
            <section className="features">
                <h2 className="sr-only">Features</h2>
                <div className="feature-item">
                    <img src="../../assets/img/icon-chat.png" alt="Chat Icon" className="feature-icon"/>
                    <h3 className="feature-item-title">You are our #1 priority</h3>
                    <p>
                        Need to talk to a representative? You can get in touch through our
                        24/7 chat or through a phone call in less than 5 minutes.
                    </p>
                </div>
                <div className="feature-item">
                    <img
                        src="../../assets/img/icon-money.png"
                        alt="Chat Icon"
                        className="feature-icon"
                    />
                    <h3 className="feature-item-title">More savings means higher rates</h3>
                    <p>
                        The more you save with us, the higher your interest rate will be!
                    </p>
                </div>
                <div className="feature-item">
                    <img
                        src="../../assets/img/icon-security.png"
                        alt="Chat Icon"
                        className="feature-icon"
                    />
                    <h3 className="feature-item-title">Security you can trust</h3>
                    <p>
                        We use top of the line encryption to make sure your data and money
                        is always safe.
                    </p>
                </div>
            </section>
        </main>
    )
}
