// front-end-bank/src/components/SignInComponent/SignInComponent.jsx
import React from "react";

export default function SignInComponent(){
    return(
        <main className="main bg-dark">
            <section className="sign-in-content">
                <i className="fa fa-user-circle sign-in-icon" />
                <h1>Sign In</h1>
                <form>
                    <div className="input-wrapper">
                        <label htmlFor="username">Username</label
                        ><input type="text" id="username"/>
                    </div>
                    <div className="input-wrapper">
                        <label htmlFor="password">Password</label
                        ><input type="password" id="password"/>
                    </div>
                    <div className="input-remember">
                        <input type="checkbox" id="remember-me"/><label htmlFor="remember-me"
                    >Remember me</label
                    >
                    </div>
                    <!-- PLACEHOLDER DUE TO STATIC SITE -->
                    <Link to="./user.html" className="sign-in-button">Sign In</Link>
                    <!-- SHOULD BE THE BUTTON BELOW -->
                    <!-- <button class="sign-in-button">Sign In</button> -->
                    <!--  -->
                </form>
            </section>
        </main>
    )
}

// front-end-angular-bank/src/app/components/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import {GenericsService} from '../../services/generics.service';
import {environment} from '../../../environments/environment';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss']
})
export class SignInComponent implements OnInit {

  constructor(
  ) { }

  ngOnInit(): void {
    // this.genericsService.getResource(`${environment.baseUrl}/api/v1`).then((response) => {
    //   console.log(response);
    // }).catch((error) => {
    //   console.error(error);
    // });
  }

}

<app-header></app-header>
<main class="main bg-dark">
  <section class="sign-in-content">
    <i class="fa fa-user-circle sign-in-icon"></i>
    <h1>Sign In</h1>
    <form>
      <div class="input-wrapper">
        <label for="username">Username</label>
        <input type="text" id="username" />
      </div>
      <div class="input-wrapper">
        <label for="password">Password</label>
        <input type="password" id="password" />
      </div>
      <div class="input-remember">
        <input type="checkbox" id="remember-me" /><label for="remember-me"
      >Remember me</label
      >
      </div>
      <!-- PLACEHOLDER DUE TO STATIC SITE -->
      <a routerLink="./" class="sign-in-button">Sign In</a>
      <!-- SHOULD BE THE BUTTON BELOW -->
      <!-- <button class="sign-in-button">Sign In</button> -->
      <!--  -->
    </form>
  </section>
</main>
