// front-end-bank/src/components/Account/Account.jsx
import React from "react";

export default function Account ({title, accountNumber, accountPrice, subTitle}) {

    return(
        <section className="account">
            <div className="account-content-wrapper">
                <h3 className="account-title">{title} ({accountNumber})</h3>
                <p className="account-amount">{accountPrice}</p>
                <p className="account-amount-description">{subTitle}</p>
            </div>
            <div className="account-content-wrapper cta">
                <button className="transaction-button">View transactions</button>
            </div>
        </section>
    )

}

// front-end-angular-bank/src/app/components/account/account.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.scss']
})
export class AccountComponent implements OnInit {

  @Input() title: any;
  @Input() accountNumber: any;
  @Input() accountPrice: any;
  @Input() subTitle: any;
  constructor() { }

  ngOnInit(): void {
  }

}

<section class="account">
  <div class="account-content-wrapper">
    <h3 class="account-title">{{title}} &nbsp;&nbsp; {{accountNumber}}</h3>
    <p class="account-amount">{{accountPrice}}</p>
    <p class="account-amount-description">{{subTitle}}</p>
  </div>
  <div class="account-content-wrapper cta">
    <button class="transaction-button">View transactions</button>
  </div>
</section>
